#!/bin/bash
# Restore the Obsidian setup: vault settings, community plugins and themes.
#
# Obsidian has no CLI to reinstall a plugin from upstream, so the four
# community plugins ship as source here — pinned to the exact versions that
# are known to work together. That is ~2 MB and the reason this repo is 4 MB
# rather than 1.8 MB; it buys an offline, version-exact restore.
#
# Vault configs mirror their $HOME-relative path under obsidian/home/, so
# adding a vault later means adding a directory, not editing this script.
#
# NOT tracked:
#   workspace.json      which notes were open — runtime state, and it leaks
#                       note titles into a public repo
#   themes/Omarchy      generated by `omarchy theme set`, per the template in
#                       /usr/share/omarchy/default/themed/obsidian.css.tpl
#   the notes themselves — this repo carries configuration, not the vault
set -euo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

log "Obsidian"

need_cmd rsync "run install/10-packages.sh first"
have obsidian || warn "obsidian is not installed — restoring its config anyway"

src_root="$DOTFILES_ROOT/obsidian/home"
[[ -d $src_root ]] || { skip "no obsidian config in repo"; exit 0; }

# Every directory under obsidian/home/ that holds a .obsidian is one vault.
mapfile -t vaults < <(cd "$src_root" && find . -type d -name .obsidian -printf '%P\n' | sed 's|/\.obsidian$||' | sort)
((${#vaults[@]})) || { skip "no vaults in repo"; exit 0; }

for rel in "${vaults[@]}"; do
  dest="$HOME/$rel/.obsidian"
  info "syncing vault config: ~/$rel"
  run mkdir -p "$dest"
  # No --delete: a vault may hold plugins or themes added on that machine only,
  # and blowing those away is not this script's call.
  run rsync -a "$src_root/$rel/.obsidian/" "$dest/"
done

# Obsidian only knows a vault once it is listed here, and
# omarchy-theme-set-obsidian reads the same file to find vaults to theme.
# Merge rather than overwrite: a machine may have vaults this repo knows nothing
# about. Vault ids are Obsidian's own 16-hex handles; deriving them from the
# path keeps a re-run from registering the same vault twice.
vault_list="$HOME/.config/obsidian/obsidian.json"
run mkdir -p "$(dirname "$vault_list")"
DRY_RUN="$DRY_RUN" VAULT_LIST="$vault_list" HOME="$HOME" python3 - "${vaults[@]}" <<'PY'
import hashlib, json, os, sys, time

path = os.environ["VAULT_LIST"]
dry = os.environ.get("DRY_RUN") == "1"
home = os.environ["HOME"]

try:
    with open(path) as fh:
        data = json.load(fh)
except (FileNotFoundError, json.JSONDecodeError):
    data = {}

vaults = data.setdefault("vaults", {})
known = {v.get("path") for v in vaults.values()}
added = []

for rel in sys.argv[1:]:
    full = os.path.join(home, rel)
    if full in known:
        continue
    vid = hashlib.md5(full.encode()).hexdigest()[:16]
    vaults[vid] = {"path": full, "ts": int(time.time() * 1000)}
    added.append(full)

if not added:
    print("    \033[2mskip\033[0m all vaults already registered with Obsidian")
elif dry:
    for full in added:
        print(f"    \033[2m[dry-run]\033[0m register vault {full}")
else:
    with open(path, "w") as fh:
        json.dump(data, fh, indent=2)
    for full in added:
        print(f"    registered vault {full}")
PY

# Regenerate the Omarchy theme inside each vault. Step 40 already ran
# `omarchy theme set`, but the vaults did not exist yet at that point.
if have omarchy-theme-set-obsidian; then
  info "syncing the Omarchy theme into the vaults"
  run omarchy-theme-set-obsidian
fi
